### ISSUE TITLE
What's needed for new release

### ISSUE THREAD

**Issue by ddorian** [moonlitesolutions/SolrClient#67]
Can you please make a list so I can create pull requests and we get a new release on pypi ?

**Comment by nickvasilyev** [comment]
Sure, I am going to put in a bit of work on this project over the weekend; it's been a bit neglected by my lately.  I want to put in something to make working with json.facet easier and fix SolrResponse a bit. 

Can you add unit tests to verify the routing is actually working correctly? I haven't looked at all the code you submitted, especially the stuff going over in the aware router. This is needed so when someone else (or me) is working on changing the transport, we can test to make sure we didn't break any of the routing functionality. Some documentation so people can figure out how to use it would be good too. 

Also, on SolrVagrant I am running into issue with indexq tests on solr 5.2.1, it looks like it is a solr 5.2.1 config issue.

**Comment by nickvasilyev** [comment]
I updated dev / master and pushed a new release (0.2.0) to pypi because of the previous bug with index method on the client, however I disabled your routing module. 

I would really like to include it next time, but I want unit tests for it to prevent breakage in the future. Having even a single unit test for the index method would definitely have identified the infinite loop and would have prevented it from being merged into the code and pushed out to pypi. I added that unit test now. 

Please add the tests for the router functionality, they can be totally independent from the rest of the tests to not mix things up. One thing you can do is to set up an extra devel argument that you can pass to the object with you instantiate it, then have it check if the flag is on and store some extra information about usage that you can later verify. Not a perfect solution, but something that would be a decent workaround. 

Let me know what you think. 
Thanks
